CREATE DATABASE api_video2;
USE api_video2;
CREATE TABLE musicas (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    ARTISTA VARCHAR(255) NOT NULL,
    ALBUM VARCHAR(255),
    GENERO VARCHAR(100),
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);
 